---
- hosts: 192.168.56.3
  become: true
  tasks:
   - name: list of install list of packages
     yum: name='{{item}}' state=present
     with_items:
       - httpd
       - wget
       - unzip
       - vim 
       - zip
       - lsof
       - tree 
      